import type { BlogPost } from "@/types/ui";

export const blogPosts: BlogPost[] = [
    {
        id: 10,
        title: 'Video Tutorial Pendaftaran Online Bagi Calon Mahasiswa Universitas Internasional Batam',
        description: 'Untuk panduan pendaftaran online, calon peserta dapat mengakses video di bawah ini. For online registration guidelines, potential participants can access the video below.',
        image: '/images/blog/10.jpg',
        author: 'HUMAS UIB',
        date: '04 Apr, 2020',
        category: 'Universitas Internasional Batam',
        detailLink: '/home/detail_informasi/10',
    },
    {
        id: 11,
        title: 'About Batam',
        description: 'Kota Batam adalah salah satu pulau di Provinsi Kepulauan Riau, yang terletak antara Selat Malaka dan Singapura yang secara keseluruhan membentuk wilayah Batam.',
        image: '/images/blog/11.jpg',
        author: 'HUMAS UIB',
        date: '03 Apr, 2020',
        category: 'Universitas Internasional Batam',
        detailLink: '/home/detail_informasi/11',
    },
    {
        id: 6,
        title: 'UIB Scholarship',
        description: 'Universitas Internasional Batam memberikan fasilitas beasiswa kepada calon mahasiswa baru sebesar 10 Miliar setiap tahunnya. Beasiswa yang diberikan terdiri dari dua macam yaitu beasiswa penuh dan beasiswa parsial (sebagian).',
        image: '/images/blog/6.jpg',
        author: 'HUMAS UIB',
        date: '02 Apr, 2020',
        category: 'Universitas Internasional Batam',
        detailLink: '/home/detail_informasi/6',
    },
    {
        id: 7,
        title: 'Student Assistance Service',
        description: 'Universitas Internasional Batam menyediakan beberapa fasilitas layanan bagi calon mahasiswa yang akan mendaftar ulang dan hadir di UIB.',
        image: '/images/blog/7.jpg',
        author: 'HUMAS UIB',
        date: '02 Apr, 2020',
        category: 'Universitas Internasional Batam',
        detailLink: '/home/detail_informasi/7',
    },
    {
        id: 5,
        title: 'Ujian Saringan Masuk Mahasiswa Baru Program Sarjana',
        description: 'Persyaratan peserta ujian saringan masuk untuk calon mahasiswa UIB.',
        image: '/images/blog/5.jpg',
        author: 'HUMAS UIB',
        date: '22 Dec, 2019',
        category: 'Universitas Internasional Batam',
        detailLink: '/home/detail_informasi/5',
    },
    {
        id: 4,
        title: 'Persyaratan Pendaftaran Mahasiswa Baru Program Sarjana TA 2024/2025',
        description: 'Pendaftaran Calon Mahasiswa Baru Program Sarjana Universitas Internasional Batam terdiri dari Jalur/Gelombang Beasiswa dan Reguler.',
        image: '/images/blog/4.jpg',
        author: 'HUMAS UIB',
        date: '15 Dec, 2019',
        category: 'Universitas Internasional Batam',
        detailLink: '/home/detail_informasi/4',
    },
    {
        id: 3,
        title: 'Informasi Biaya Kuliah Mahasiswa Baru Program Sarjana TA 2024/2025',
        description: 'Biaya Kuliah Calon Mahasiswa Baru TA 2024/2025 terbagi atas Gelombang Beasiswa dan Reguler.',
        image: '/images/blog/3.jpg',
        author: 'HUMAS UIB',
        date: '14 Dec, 2019',
        category: 'Universitas Internasional Batam',
        detailLink: '/home/detail_informasi/3',
    },
    {
        id: 2,
        title: 'Komposisi Soal Ujian Saringan Masuk Mahasiswa Baru Program Sarjana',
        description: 'Komposisi Ujian Saringan Masuk bagi seluruh peserta yang mendaftar sebagai mahasiswa baru program Sarjana adalah sama dan dilaksanakan secara bersamaan, dengan total 100 soal yang terdiri dari:',
        image: '/images/blog/2.jpg',
        author: 'HUMAS UIB',
        date: '01 Dec, 2019',
        category: 'Universitas Internasional Batam',
        detailLink: '/home/detail_informasi/2',
    },
    {
        id: 1,
        title: 'Informasi Tempat Tinggal Terdekat Mahasiswa Universitas Internasional Batam',
        description: 'Informasi Asrama UIB',
        image: '/images/blog/1.jpg',
        author: 'HUMAS UIB',
        date: '01 Nov, 2019',
        category: 'Universitas Internasional Batam',
        detailLink: '/home/detail_informasi/1',
    },
];
