[DEFAULT]
db_url = sqlite:////var/lib/clamav/fangfrisch.db
local_directory = /var/lib/clamav
log_level = INFO

[sanesecurity]
enabled = yes

[urlhaus]
enabled = yes

[interserver]
enabled = yes
