export const BREADCRUMB_LABELS: Record<string, string> = {
    '': 'Beranda',
    'info-umum': 'Informasi Umum',
    'panduan': 'Panduan',
    'login': 'Login',
    'register': 'Daftar Akun',
    'forgot-password': 'Lupa Password',
    'reset-password': 'Reset Password',
    'verify-email': 'Verifikasi Email',
    'check-inbox': 'Cek Inbox',
    'account': 'Akun Saya',
    'update-profile': 'Perbarui Profil',
    'change-password': 'Ubah Password',
    'prasyarat-ospek': 'Prasyarat Ospek',
    'prodi': 'Prodi',
    'change-prodi': 'Ganti Prodi',
    'transfer-proof': 'Bukti Pembayaran',
    'upload-transfer-proof': 'Upload Bukti Pembayaran',
    'batch-registration': 'Pendaftaran Gelombang',
};
